### ISSUE TITLE
JsonException Syntax error in FileStorageDriver

### ISSUE THREAD

**Issue by elephantux** [defstudio/telegraph#378]
I have the following code:
```
$response = $this-chat->html($message)->send();
$rsBody = json_decode($response->body());
if (isset($rsBody->result->message_id)) {
    $this->chat->storage()->set('subscription_buttons_msg_id', $rsBody->result->message_id);
}
```

But in spite of checking and presence of number in variable ($rsBody->result->message_id) I get error:

```
Syntax error {"exception":"[object] (JsonException(code: 4): Syntax error at /var/www/5pclub/vendor/defstudio/telegraph/src/Storage/FileStorageDriver.php:39)
[stacktrace]
#0 /var/www/5pclub/vendor/defstudio/telegraph/src/Storage/FileStorageDriver.php(39): json_decode('', true, 512, 4194304)
#1 /var/www/5pclub/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(740): DefStudio\\Telegraph\\Storage\\FileStorag
#2 /var/www/5pclub/vendor/defstudio/telegraph/src/Storage/FileStorageDriver.php(39): rescue(Object(Closure), Array))
```

It seems to me that the error does not appear on every request. Because the storage is full of json files with saved values.

I can't figure out what this could be about. What do you think?

**Comment by BeyCoder** [comment]
up

**Comment by elephantux** [comment]
@BeyCoder do you have similar errors?

**Comment by BeyCoder** [comment]
> @BeyCoder do you have similar errors?

Yeah, I have these exceptions in logs, but everything is working perfectly 😁

**Comment by fabio-ivona** [comment]
Can't manage to reproduce, it seems that telegram returns an invalid json as response

Any way you can log the raw response?

**Comment by EvgRass** [comment]
Issue Description:

When using the `$json = $this->disk->get($this->file);` method and the file is absent, the returned value of `$json` is null. Subsequently, attempting to execute `json_decode($json, true, flags: JSON_THROW_ON_ERROR)` results in a JsonException due to the inappropriate value.

Proposed Fix:

After the `$json = $this->disk->get($this->file);` line, add a check for null and an empty string:

```
if (is_null($json) || $json === '') {
    return [];
}
```
This will prevent an error when attempting to decode null and ensure the code executes correctly even when the file is absent.

**Comment by pepperfm** [comment]
@fabio-ivona @MarioGattolla 
hi there https://github.com/defstudio/telegraph/pull/773
