### ISSUE TITLE
after updating the package I get an error when sending a photo maxSizeInMb

### ISSUE THREAD

**Issue by m-petrosyan** [defstudio/telegraph#517]
![image](https://github.com/defstudio/telegraph/assets/34434297/8172181b-d4d8-435a-8651-fe60a958f223)

```
[2024-02-14 00:06:25] local.ERROR: assert(is_float($maxSizeInMb)) {"exception":"[object] (AssertionError(code: 1): assert(is_float($maxSizeInMb)) at D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\defstudio\\telegraph\\src\\Concerns\\SendsAttachments.php:297)
[stacktrace]
#0 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\defstudio\\telegraph\\src\\Concerns\\SendsAttachments.php(297): assert(false, 'assert(is_float...')
#1 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\defstudio\\telegraph\\src\\Concerns\\SendsAttachments.php(233): DefStudio\\Telegraph\\Telegraph->attachPhoto(Object(DefStudio\\Telegraph\\Telegraph), 'storage/1/17078...', NULL)
#2 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\app\\Telegram\\TelegramEvents.php(19): DefStudio\\Telegraph\\Telegraph->photo('storage/1/17078...')
#3 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): App\\Telegram\\TelegramHandler->eventsList('eventsList')
#4 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#6 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#7 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#8 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(355): Illuminate\\Container\\Container->call(Array, Array)
#9 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\defstudio\\telegraph\\src\\Handlers\\WebhookHandler.php(70): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#10 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\defstudio\\telegraph\\src\\Handlers\\WebhookHandler.php(257): DefStudio\\Telegraph\\Handlers\\WebhookHandler->handleCallbackQuery()
#11 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\defstudio\\telegraph\\src\\Controllers\\WebhookController.php(28): DefStudio\\Telegraph\\Handlers\\WebhookHandler->handle(Object(Illuminate\\Http\\Request), Object(App\\Models\\Bot))
#12 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(46): DefStudio\\Telegraph\\Controllers\\WebhookController->handle(Object(Illuminate\\Http\\Request), '6744946968:AAGx...')
#13 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(DefStudio\\Telegraph\\Controllers\\WebhookController), 'handle')
#14 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(205): Illuminate\\Routing\\Route->runController()
#15 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(806): Illuminate\\Routing\\Route->run()
#16 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(805): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#19 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#20 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(748): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#21 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#22 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#23 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#24 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#41 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\public\\index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#42 D:\\wamp64\\www\\projects\\metal-events-telegram-bot\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\resources\\server.php(16): require_once('D:\\\\wamp64\\\\www\\\\p...')
#43 {main}
"} 

```

**Comment by fabio-ivona** [comment]
@m-petrosyan could you please share the value of your config file in `telegraph.attachments.photo.max_size_mb`?

**Comment by m-petrosyan** [comment]
@fabio-ivona  
![image](https://github.com/defstudio/telegraph/assets/34434297/0c94d17b-856a-4168-9533-b4e041a4f766)

**Comment by fabio-ivona** [comment]
@m-petrosyan can't reproduce. which version of php are you using?

**Comment by fabio-ivona** [comment]
nevermind, fixed

**Comment by m-petrosyan** [comment]
@fabio-ivona 
 "defstudio/telegraph": "^1.41",

**Comment by m-petrosyan** [comment]
@fabio-ivona 
in v1.41.2 everything works, thanks
